name: On Push

on:
  push:
    branches: [ master ]

jobs:
  build_and_release:
    name: Build (and Release)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build
        run: ./gradlew clean build
      - name: Publish to Curseforge
        run: ./gradlew curseforge
        if: "contains(github.event.head_commit.message, '[release]')"
        env:
          CURSEKEY: ${{ secrets.CURSEKEY }}
      - name: Publish to Modrinth
        run: ./gradlew publishModrinth
        if: "contains(github.event.head_commit.message, '[release]')"
        env:
          MODRINTHKEY: ${{ secrets.MODRINTHKEY }}
